# Generated by Django 4.0.3 on 2022-04-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mark',
            field=models.TextField(max_length=10),
        ),
    ]
