# Generated by Django 4.0.4 on 2022-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docker_image_name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(default='on moderate', max_length=255),
        ),
        migrations.DeleteModel(
            name='DockerISO',
        ),
    ]
