# Generated by Django 4.0.4 on 2022-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(default='OnModerate', max_length=255),
        ),
    ]
