# Generated by Django 4.0.4 on 2022-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_docker_image_name_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docker_status',
            field=models.TextField(default='declined', max_length=255),
        ),
    ]
