# Generated by Django 4.0.2 on 2022-03-28 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
