# Generated by Django 4.0.2 on 2022-03-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_upload_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docker_ISO',
            new_name='DockerISO',
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
