# Generated by Django 4.0.2 on 2022-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_docker_iso_dockeriso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='status',
            field=models.TextField(default='ordinary', max_length=255),
        ),
    ]
