# Generated by Django 4.0.4 on 2022-05-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
