# Generated by Django 4.0.3 on 2022-04-04 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_images_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
