# Generated by Django 4.0.4 on 2022-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.TextField(default='unread', max_length=100),
        ),
    ]
